/*
 * _____                    _
 *|_   _|_      _____ _ __ | |_ _   _
 *  | | \ \ /\ / / _ \ '_ \| __| | | | Auto-generated file
 *  | |  \ V  V /  __/ | | | |_| |_| | Any edits to this will be overridden
 *  |_|   \_/\_/ \___|_| |_|\__|\__, | Generated by: bun run version:bump in packages/twenty-server
 *                              |___/
 */

export const TWENTY_CURRENT_VERSION = '2.44.0' as const;
